"""add created_at

Revision ID: 0b94faede48b
Revises: 34d5aaf8a9b8
Create Date: 2026-08-11 14:30:46.287489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b94faede48b'
down_revision: Union[str, Sequence[str], None] = '34d5aaf8a9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'todo',
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )

    op.execute(
        sa.text(
            "UPDATE todo SET created_at = CURRENT_TIMESTAMP "
            "WHERE created_at IS NULL"
        )
    )

    with op.batch_alter_table("todo") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            nullable=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'created_at')
    # ### end Alembic commands ###
